// <auto-generated />
namespace Ecommerce.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _OrderTableEdited : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_OrderTableEdited));
        
        string IMigrationMetadata.Id
        {
            get { return "202112271848073__OrderTableEdited"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
